/**
 * Listing Lab — build the owner's dashboard page from the design Kyle already
 * approved (the "Listing Lab Dashboard" artifact, 22 Aug). The design is kept
 * byte-for-byte where possible; what changes is only what makes it REAL:
 *
 *   - the artifact frame-runtime wrapper is stripped, a clean head added
 *   - the mock `const ADMIN = {…}` becomes an injection token the worker fills
 *     with live D1 numbers on every request
 *   - the mock localStorage service switches become real calls to
 *     /internal/board/flags, which every customer request honors
 *
 * Output: src/board-page.js exporting the page with __ADMIN_DATA__,
 * __SVC_DATA__ and __BOARD_SECRET__ tokens.
 *
 * Run: node scripts/build-board.mjs <path-to-saved-artifact.html>
 */
import { readFileSync, writeFileSync } from 'fs';

const src = process.argv[2];
if (!src) { console.error('usage: node scripts/build-board.mjs <artifact.html>'); process.exit(1); }
let h = readFileSync(src, 'utf8');

// 1. Strip the artifact wrapper: keep everything after its injected head.
const bodyStart = h.indexOf('</head><body>');
if (bodyStart === -1) throw new Error('wrapper head not found');
let body = h.slice(bodyStart + '</head><body>'.length);
body = body.replace(/<\/body><\/html>\s*$/, '');
// The wrapper's stray title/meta at the top of body stay harmless; the real
// <title> below wins in practice, but remove the duplicate meta viewport.
body = body.replace('<title>Listing Lab Dashboard</title>', '');
body = body.replace('<meta name="viewport" content="width=device-width, initial-scale=1" />', '');

// 2. Replace the mock ADMIN block with the injection token.
const aStart = body.indexOf('const ADMIN = {');
const aEnd = body.indexOf('function roundedTopRect');
if (aStart === -1 || aEnd === -1 || aEnd < aStart) throw new Error('ADMIN block not found');
body = body.slice(0, aStart) + 'const ADMIN = __ADMIN_DATA__;\n\n' + body.slice(aEnd);

// 3. Real service switches: state injected by the worker, toggles POST to it.
const gStart = body.indexOf('function getService(){');
const gEnd = body.indexOf('/* toggle bindings for before/original views');
if (gStart === -1 || gEnd === -1 || gEnd < gStart) throw new Error('service block not found');
body = body.slice(0, gStart) + `let __SVC = __SVC_DATA__;
function getService(){ return __SVC; }
window.LL.svcToggle = function(k, v){
  const prev = { ...__SVC };
  __SVC[k] = v; render();
  fetch('/internal/board/flags?s=' + encodeURIComponent(__BOARD_SECRET__), {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ key: k, value: v }),
  }).then(r => {
    if (!r.ok) throw new Error('HTTP ' + r.status);
    toast(v ? 'Paused — customers see the paused notice immediately.' : 'Resumed — back to normal for all customers.');
  }).catch(() => { __SVC = prev; render(); toast('Could not save that — nothing changed.'); });
};

` + body.slice(gEnd);

// 4. The "Open Listing Lab" link goes to the live product, not the artifact.
body = body.replace(/href="https:\/\/claude\.ai\/code\/artifact\/[^"]*"/g, 'href="/"');

// 5. Clean standalone document.
const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Listing Lab dashboard</title>
<meta name="robots" content="noindex, nofollow">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600;9..144,700&family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
</head><body>
${body}
</body></html>`;

const out = `/**
 * Listing Lab — the owner's dashboard page. GENERATED by scripts/build-board.mjs
 * from the approved dashboard design; do not edit by hand — edit the builder.
 * The worker fills __ADMIN_DATA__, __SVC_DATA__ and __BOARD_SECRET__ at serve
 * time. Never linked from the customer product.
 */
export const BOARD_PAGE = ${JSON.stringify(page)};
`;
writeFileSync(new URL('../src/board-page.js', import.meta.url), out);
console.log('src/board-page.js written: %d KB page', Math.round(page.length / 1024));
